version: '3'
services:
    api:
        command: sh -c "cargo run --release"
    website:
        environment:
            PORT: '80'
        command: sh -c "npm install && npm run build && node build"
        ports:
            - 80:80