services:
    api:
        build: ./api
        image: cookbook/api
        volumes:
            - './api:/code'
        command: sh -c "cargo watch -x run"
        environment:
            DATABASE_URL: '${API_DB_URL}'
            STORAGE_URL: '${API_STORAGE_URL}'
            SECRET: '${API_SECRET}'
            CARGO_TARGET_DIR: '/build'
        network_mode: host
    website:
        build: ./website
        image: cookbook/website
        volumes:
            - './website:/code'
        command: sh -c "npm install && npm run dev -- --host"
        environment:
            PUBLIC_API_URL: '${SVELTE_API_URL}'
        network_mode: host
    database:
        image: 'mysql/mysql-server:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'database:/var/lib/mysql'
        network_mode: host
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    files:
        image: 'sigoden/dufs'
        volumes:
            - 'files:/data'
        command: '/data -A -a ${DUFS_AUTH}'
        network_mode: host
volumes:
    database:
        driver: local
    files:
        driver: local
