version: '3'
services:
    api:
        build: ./api
        image: cookbook/api
        volumes:
            - './api:/code'
        command: sh -c "cargo watch -x run"
        environment:
            DATABASE_URL: '${API_DB_URL}'
            STORAGE_URL: '${API_STORAGE_URL}'
            SECRET: '${API_SECRET}'
            CARGO_TARGET_DIR: '/build'
        ports:
            - 8000:8000
        networks:
            - cb
    website:
        build: ./website
        image: cookbook/website
        volumes:
            - './website:/code'
        command: sh -c "npm install && npm run dev -- --host"
        environment:
            PUBLIC_BROWSER_API_URL: '${SVELTE_BROWSER_API_URL}'
            PUBLIC_SERVER_API_URL: '${SVELTE_SERVER_API_URL}'
        ports:
            - 5173:5173
        networks:
            - cb
    database:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'database:/var/lib/mysql'
        networks:
            - cb
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    files:
        image: 'sigoden/dufs'
        ports:
            - 5000:5000
        volumes:
            - 'files:/data'
        command: '/data -A -a ${DUFS_AUTH}'
        networks:
            - cb
networks:
    cb:
        driver: bridge
volumes:
    database:
        driver: local
    files:
        driver: local
