services:
    api:
        volumes:
            - './cert:/cert'
        environment:
            PRODUCTION: 'true'
        command: sh -c "sqlx migrate run && cargo run --release"
    website:
        volumes:
            - './cert:/cert'
        environment:
            PUBLIC_API_URL: '${SVELTE_PROD_API_URL}'
        command: sh -c "npm install && npm run build && node server.js"
