version: '3'
services:
    api:
        build: ./api
        image: api/cookbook
        volumes:
            - type: bind
              source: ./api
              target: /code
        command: sh -c "cargo watch -x run"
        environment:
            DATABASE_URL: '${DB_URL}'
        ports:
            - 8000:8000
        networks:
            - cb
        user: '${UID}:${GID}'
    website:
        build: ./website
        image: website/cookbook
        volumes:
            - type: bind
              source: ./website
              target: /code
        command: sh -c "npm install && npm run dev"
        ports:
            - 3000:3000
        networks:
            - cb
        user: '${UID}:${GID}'
    database:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'database:/var/lib/mysql'
        networks:
            - cb
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
networks:
    cb:
        driver: bridge
volumes:
    database:
        driver: local